name: Convert Arxiv URLs to IDs

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  convert-urls-to-ids:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.x'

    - name: Convert IDs to URLs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
      run: |
        pip install -r requirements.txt
        python scripts/convert_arxiv_urls_to_ids.py

        # commit and push if changes
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add github_stars.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update star lists data" && git push)
